server:
  port: 9003
spring:
  application:
    name: house-api
zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:8082/consumer/
eureka:
  client:
    service-url:
      defaultZone: http://dc:19851218@localhost:8761/eureka/